### ISSUE TITLE
Can't get this to work with my gradle project

### ISSUE THREAD

**Issue by aimeejtix** [JavaanseHZ/cluecumber-report-gradle-plugin#5]
Hi, 

I didn't know where else to contact you! 
I am trying to use this in my project and for some reason it can't find this project. 

```
plugins {
    kotlin("jvm")
    id("se.thinkcode.cucumber-runner") version "0.0.8"
    id("de.javaansehz.cluecumber-report-gradle-plugin")
}
```
The error is: `Plugin with id 'de.javaansehz.cluecumber-report-gradle-plugin' not found.`

Do you have any ideas why this is happening? 

Thanks,
Aimee

**Comment by JavaanseHZ** [comment]
Hi Aimee,

I think you have to specify the plugin version like so:

id "de.javaansehz.cluecumber-report-gradle-plugin" version "1.1.4"

There's a minimal example here:
https://github.com/JavaanseHZ/cluecumber-report-gradle-plugin-example

Cheers,
Ben

**Comment by JavaanseHZ** [comment]
Thanks for catching that - i updated the readme.

**Comment by aimeejtix** [comment]
Thanks for getting back to me.
So I got a bit further and now I see this error:
`com.google.common.collect.MapMaker.makeComputingMap(Lcom/google/common/base/Function;)Ljava/util/concurrent/ConcurrentMap;` 
(not a very useful error!)

Could this be an issue with a dependency of yours? Or maybe a conflict between our dependencies...

**Comment by JavaanseHZ** [comment]
hmm, could be - i updated the guice dependency to the newest version now.

the plugin is now version 1.1.5: https://plugins.gradle.org/plugin/de.javaansehz.cluecumber-report-gradle-plugin

could you try if the minimal example works for you?
after cloning it should just be ./gradlew generateCluecumberReports

**Comment by aimeejtix** [comment]
The minimal example works! Must be something in my project. 

Thanks a mill for trying to help out! I'll close this issue
