### ISSUE TITLE
Cluecumber 2.5.0

### ISSUE THREAD

**Issue by karatekid5088** [JavaanseHZ/cluecumber-report-gradle-plugin#6]
Hello,

This is a great plugin. I can see it is currently pointing to Cluecumber 2.2.0. 
I just wondered if you have plans to point to a later version e.g. 2.5.0 (https://github.com/trivago/cluecumber-report-plugin/releases/tag/2.5.0)?

Thanks.

**Comment by JavaanseHZ** [comment]
Sure, I can create a new version tonight, if the api didn’t change much. Otherwise it might take a bit longer.
I’ll see if I can automate it at some point.

**Comment by JavaanseHZ** [comment]
not sure why the release doesn't show up on the plugin portal - i'll wait a bit and check in later :/

**Comment by JavaanseHZ** [comment]
@karatekid5088 
new version 1.2.1 is out, supporting the new startPage configuration parameter.
[see gradle plugin portal](https://plugins.gradle.org/plugin/de.javaansehz.cluecumber-report-gradle-plugin)

**Comment by karatekid5088** [comment]
@JavaanseHZ working perfectly - thank you so much :)
