### ISSUE TITLE
Unable to load class 'com.trivago.cluecumber.exceptions.CluecumberPluginException'.

### ISSUE THREAD

**Issue by pmehaboobkhan** [JavaanseHZ/cluecumber-report-gradle-plugin#8]
When applying gradle plugin as below for version 1.2.1, getting attached errors:
**_apply plugin: "de.javaansehz.cluecumber-report-gradle-plugin"_**

<img width="756" alt="image" src="https://user-images.githubusercontent.com/50671697/88242301-c7d57700-cc5a-11ea-976f-289951509e01.png">

<img width="1600" alt="image" src="https://user-images.githubusercontent.com/50671697/88242245-a6748b00-cc5a-11ea-8482-e252d3bfdf84.png">
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/50671697/88242259-ad030280-cc5a-11ea-866b-228f26f2bf73.png">

Has anyone faced same issue on when applying 1.2.1 version as gradle plugin.

**Comment by pmehaboobkhan** [comment]
@JavaanseHZ : FYI, anyhelp would be appreciated. Thank you.

**Comment by JavaanseHZ** [comment]
Ah, sorry, I saw it originally and then forgot about it. Did you solve it yourself or do you still need help?

**Comment by pmehaboobkhan** [comment]
Yeah, Repository reference was wrong. I fixed it by re-uploading your plugin to artifactory and it worked. Thanks for checking on this.
